/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.ResultSet;

import javax.swing.JOptionPane;

/**
 *
 * @author Vitor
 */
public class criarProgramacao extends javax.swing.JFrame {
    private int idFilme;

    
    public criarProgramacao(int idFilme) {
        this.idFilme = idFilme;
        initComponents();
        carregarDadosFilme(idFilme);

    }

    private void carregarDadosFilme(int idFilme) {
        try {
            appData app = new appData();
            ResultSet rs = app.buscarFilmePorId(idFilme);
            if (rs.next()) {
                txtTitulo.setText(rs.getString("titulo"));
                txtDiretor.setText(rs.getString("diretor"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados do filme!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiretor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        btnEnviarProgramacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Título do Filme:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 30, 100, 30);
        getContentPane().add(txtTitulo);
        txtTitulo.setBounds(150, 30, 270, 30);

        jLabel4.setText("Diretor:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 70, 110, 30);

        txtDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiretorActionPerformed(evt);
            }
        });
        getContentPane().add(txtDiretor);
        txtDiretor.setBounds(120, 70, 300, 30);

        jLabel3.setText("Data:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 100, 30);
        getContentPane().add(txtData);
        txtData.setBounds(120, 110, 170, 30);

        jLabel5.setText("Hora:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 150, 110, 30);

        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        getContentPane().add(txtHora);
        txtHora.setBounds(120, 150, 170, 30);

        jLabel7.setText("Local:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 190, 110, 30);

        txtLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalActionPerformed(evt);
            }
        });
        getContentPane().add(txtLocal);
        txtLocal.setBounds(120, 190, 300, 30);

        btnEnviarProgramacao.setText("Enviar  Programação");
        btnEnviarProgramacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarProgramacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviarProgramacao);
        btnEnviarProgramacao.setBounds(170, 240, 140, 40);

        setSize(new java.awt.Dimension(517, 364));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiretorActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalActionPerformed

    private void btnEnviarProgramacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarProgramacaoActionPerformed
        String data = txtData.getText();
        String hora = txtHora.getText();
        String local = txtLocal.getText();
        String titulo = txtTitulo.getText();
        String diretor = txtDiretor.getText();

        try {
            new appData().criarProgramacao(idFilme, titulo, diretor, data, hora, local);
            JOptionPane.showMessageDialog(null, "Programação enviada com sucesso!");

            txtTitulo.setText("");
            txtDiretor.setText("");
            txtData.setText("");
            txtHora.setText("");
            txtLocal.setText("");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o Driver JDBC");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar criar a programação: " + e.getMessage());
        }

    }//GEN-LAST:event_btnEnviarProgramacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(criarProgramacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(criarProgramacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(criarProgramacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(criarProgramacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new criarProgramacao(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarProgramacao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDiretor;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
