/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.ResultSet;

import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitor
 */
public class editarAvaliacao extends javax.swing.JFrame {

    private int idAvaliacao;

    public editarAvaliacao(int idAvaliacao) {
        this.idAvaliacao = idAvaliacao;
        initComponents();
        carregarDadosAvaliacao(idAvaliacao);
    }

    private void carregarDadosAvaliacao(int idAvaliacao) {
        try {
            appData app = new appData();
            ResultSet rs = app.buscarAvaliacao(idAvaliacao);
            if (rs.next()) {
                txtTitulo.setText(rs.getString("titulo"));
                txtDiretor.setText(rs.getString("diretor"));
                cnbGenero.setSelectedItem(rs.getString("genero"));
                txtDuracao.setText(rs.getString("duracao"));
                txtData.setText(rs.getString("data_lancamento"));
                cnbClassificacao.setSelectedItem(rs.getString("classificacao_indicativa"));
                // Desabilitar edição dos campos que não devem ser editados
                txtTitulo.setEnabled(false);
                txtDiretor.setEnabled(false);
                cnbGenero.setEnabled(false);
                txtDuracao.setEnabled(false);
                txtData.setEnabled(false);
                cnbClassificacao.setEnabled(false);
                // Permitir a edição dos campos desejados
                txtCinematografia.setText(rs.getString("cinematografia"));
                txtOriginalidade.setText(rs.getString("originalidade"));
                txtComentario.setText(rs.getString("comentario_tecnico"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher campos!" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiretor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cnbGenero = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtDuracao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cnbClassificacao = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtCinematografia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtOriginalidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtComentario = new javax.swing.JTextField();
        btnEditarAvaliacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Título do Filme:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 30, 100, 30);
        getContentPane().add(txtTitulo);
        txtTitulo.setBounds(150, 30, 270, 30);

        jLabel4.setText("Diretor:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 70, 110, 30);

        txtDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiretorActionPerformed(evt);
            }
        });
        getContentPane().add(txtDiretor);
        txtDiretor.setBounds(120, 70, 300, 30);

        jLabel3.setText("Gênero:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 110, 30);

        cnbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Romance", "Aventura", "Suspense", "Terror/Horror", "Ação", "Documentário", "Ficção científica", "Drama", "Comédia", "Fantasia", "Musical", "Mistério" }));
        cnbGenero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cnbGeneroItemStateChanged(evt);
            }
        });
        getContentPane().add(cnbGenero);
        cnbGenero.setBounds(120, 110, 300, 30);

        jLabel1.setText("Duração:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 150, 110, 30);

        txtDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDuracao);
        txtDuracao.setBounds(120, 150, 300, 30);

        jLabel5.setText("Data Lançamento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 190, 110, 30);

        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });
        getContentPane().add(txtData);
        txtData.setBounds(190, 190, 230, 30);

        jLabel7.setText("Classificação indicativa:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 230, 130, 30);

        cnbClassificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "10 anos", "12 anos", "14 anos", "16 anos", "18 anos" }));
        getContentPane().add(cnbClassificacao);
        cnbClassificacao.setBounds(190, 230, 230, 30);

        jLabel8.setText("Cinematografia:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 270, 100, 30);
        getContentPane().add(txtCinematografia);
        txtCinematografia.setBounds(150, 270, 270, 30);

        jLabel9.setText("Originalidade:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 310, 100, 30);
        getContentPane().add(txtOriginalidade);
        txtOriginalidade.setBounds(150, 310, 270, 30);

        jLabel10.setText("Comentário Técnico:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 350, 150, 30);
        getContentPane().add(txtComentario);
        txtComentario.setBounds(180, 350, 240, 90);

        btnEditarAvaliacao.setText("Editar Avaliação");
        btnEditarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAvaliacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarAvaliacao);
        btnEditarAvaliacao.setBounds(200, 460, 190, 40);

        setSize(new java.awt.Dimension(812, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiretorActionPerformed

    private void cnbGeneroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cnbGeneroItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cnbGeneroItemStateChanged

    private void txtDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracaoActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void btnEditarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAvaliacaoActionPerformed
        try {
            appData app = new appData();
            app.editarAvali(
                idAvaliacao,
                txtTitulo.getText(),
                txtDiretor.getText(),
                cnbGenero.getSelectedItem().toString(),
                txtDuracao.getText(),
                txtData.getText(),
                cnbClassificacao.getSelectedItem().toString(),
                txtCinematografia.getText(),
                txtOriginalidade.getText(),
                txtComentario.getText()
            );
            JOptionPane.showMessageDialog(null, "Avaliação editada com sucesso!");
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao editar avaliação!");
        }
    }//GEN-LAST:event_btnEditarAvaliacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editarAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editarAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editarAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editarAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editarAvaliacao(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarAvaliacao;
    private javax.swing.JComboBox<String> cnbClassificacao;
    private javax.swing.JComboBox<String> cnbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCinematografia;
    private javax.swing.JTextField txtComentario;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDiretor;
    private javax.swing.JTextField txtDuracao;
    private javax.swing.JTextField txtOriginalidade;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
