/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vitor
 */
public class listarSubmissao extends javax.swing.JFrame {

    
    appData data;
    /**
     * Creates new form listarSubmissao
     */
    public listarSubmissao() {
        initComponents();
        data = new appData();
        carregarDados("Todos");
    }

    public void carregarDados(String genero){
        try {
            DefaultTableModel model = (DefaultTableModel) tblSubmissoes.getModel();
            model.setRowCount(0);
            ResultSet resultado = data.listarFilmes(genero);
            while (resultado.next()) {
                model.addRow(new Object[]{
                    resultado.getInt("id_filme"), 
                    resultado.getString("titulo"), 
                    resultado.getString("genero"), 
                    resultado.getString("diretor")
                });
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao buscar filmes: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblCargo = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        btnListarSubmissoes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubmissoes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        iblCargo.setText("Gênero:");
        getContentPane().add(iblCargo);
        iblCargo.setBounds(180, 40, 100, 50);

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Romance", "Aventura", "Suspense", "Terror/Horror", "Ação", "Documentário", "Ficção científica", "Drama", "Comédia", "Fantasia", "Musical", "Mistério", "Todos" }));
        cmbGenero.setSelectedItem("Todos");
        cmbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(cmbGenero);
        cmbGenero.setBounds(230, 50, 170, 30);

        btnListarSubmissoes.setText("Listar");
        btnListarSubmissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarSubmissoesActionPerformed(evt);
            }
        });
        getContentPane().add(btnListarSubmissoes);
        btnListarSubmissoes.setBounds(410, 50, 150, 40);

        tblSubmissoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID do filme", "Título", "Gênero", "Diretor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSubmissoes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 740, 330);

        setSize(new java.awt.Dimension(821, 504));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGeneroActionPerformed
        String genero = cmbGenero.getSelectedItem().toString();
        carregarDados(genero);
    }//GEN-LAST:event_cmbGeneroActionPerformed

    private void btnListarSubmissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarSubmissoesActionPerformed
        String genero = cmbGenero.getSelectedItem().toString();
        carregarDados(genero);
    }//GEN-LAST:event_btnListarSubmissoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listarSubmissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listarSubmissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listarSubmissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listarSubmissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listarSubmissao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarSubmissoes;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JLabel iblCargo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSubmissoes;
    // End of variables declaration//GEN-END:variables
}
